language: bash
sudo: required
services:
  - docker

before_install:
  - docker pull golang:1.7.5
  - docker pull node:6.11.0-slim
  - docker pull f5devcentral/containthedocs

script:
  - set -e
  - docker run --rm -it -v `pwd`:`pwd` -w `pwd` node:6.11.0-slim build-tools/schema-tests.sh
  - if [ "$DOCKER_NAMESPACE" == "" ]; then DOCKER_NAMESPACE="local"; fi
  - BASE_PUSH_TARGET="$DOCKER_NAMESPACE/k8s-bigip-ctlr"
  - |
    if [ "$DOCKER_P" == "" -o "$DOCKER_U" == "" -o $DOCKER_NAMESPACE == "" ]; then
      echo "[INFO] Docker user, password, or namespace vars absent from travis-ci."
      echo "[INFO] See README.md section 'build' to configure travis with DockerHub."
    else
      docker login -u="$DOCKER_U" -p="$DOCKER_P"
      DOCKER_READY="true"
    fi
  - export IMG_TAG="${BASE_PUSH_TARGET}:${TRAVIS_COMMIT}"
  - export BUILD_IMG_TAG="${BASE_PUSH_TARGET}-devel:${TRAVIS_COMMIT}"
  - export CLEAN_BUILD=true
  - export BASE_OS=alpine
  - export CTLR_VERSION=$(echo $TRAVIS_BRANCH | sed s/-stable//g)
  - ./build-tools/build-devel-image.sh
  - ./build-tools/run-in-docker.sh make verify
  - ./build-tools/build-debug-artifacts.sh
  - ./build-tools/build-release-artifacts.sh
  - ./build-tools/build-release-images.sh
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
  - docker tag "$IMG_TAG" "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
  - |
    if [ "$DOCKER_READY" ]; then
      docker push "$IMG_TAG"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH"
      docker push "$BASE_PUSH_TARGET:devel-$TRAVIS_BRANCH-n-$TRAVIS_BUILD_NUMBER-id-$TRAVIS_BUILD_ID"
    fi
  - make docs

deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
      repo: F5Networks/k8s-bigip-ctlr
      condition: $TRAVIS_BRANCH == *"-stable"
    script:
      - ./build-tools/deploy-docs.sh publish-product-docs-to-prod connectors/k8s-bigip-ctlr $CTLR_VERSION

notifications:
  slack:
    rooms:
      # k8s channel
      - secure: DviXu1iLQaBbF3ya4PLvy/ln6OLTmhCOM3EJBsQpzCWG/YtdONKgOrSNTOqOu1iq3AcUehE2svSgTtg+9qvG+S5iiHwZ0QfJOvTWMr0CogNhb8S8/fVd66UP4oewdJOtyOTNj1F8AQld+8lJR39ZOgkeBKmTQduxv+rt3iJVHuBx9MLbiOTOYVlFQ4mQ+xkAMUPp/fuosjYCyeDYaWrQv6sWISnHShWV8cceCqyeSs+h3I8KOdNmsONkD6z1goqE5UbtZ5rUPLGU70FEoyG1lUCaLNq7f0oDpZGEYPPl9WhDUA1HVEiaArl0w7AneDDz0U5S2V2mwAWG+KYNyMtb5YYkzI2MccqiIPJiux+nUnpXy0cbwrRO1gg5L656dRshM78vp6MHVKDWo8cG+Xz4r6VsEbna3wA0fuIm1XrI/idTH4exGsf5NdoRjITCsNw6tdwaql+RdfMuzvHEd3GWb5oU+nuSf9HTsl4RD5kkNUBquQln/P0motyNmqTP2kCazO/AphV08k7cKxEWdfdR62ETs289spYWa7szGXv2sm/u6r2DakBNLWX6lQbDYRtWBVWclCrH5i1S7yANOnzzgiX4QCQ8Dtg++VvSDrPpH/Q0lYgyw0InPOJIeL1QiUmvVLeCFZnVANQbnn8bLWOJGAl82t2tvRLOT0OOUw+gic0=
    on_success: change
    on_failure: always
    on_pull_requests: false
