kind: ConfigMap
apiVersion: v1
metadata:
  name: hubmode-configmap
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
    isTenantNameServiceNamespace: "true"
data:
  template: |
    {
        "class": "AS3",
        "action": "deploy",
        "persist": true,
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.25.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d-fooc4075977",
            "label": "foo-cm-hubmode",
            "remark": "AS3 Declation for foo-cm-hubmode",
            "foo": {
                "class": "Tenant",
                "fooapp": {
                    "class": "Application",
                    "template": "http",
                    "serviceMain": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.145.0.5"
                        ],
                        "pool": "foopool",
                        "persistenceMethods": []
                    },
                    "foopool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "shareNodes": false,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "barapp": {
                    "class": "Application",
                    "template": "http",
                    "serviceMain": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.145.0.7"
                        ],
                        "pool": "barpool",
                        "persistenceMethods": []
                    },
                    "barpool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "shareNodes": false,
                                "serverAddresses": []
                            }
                        ]
                    },
                }
            }
        }
    }
