apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-basic
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-basic
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-balance
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-balance
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-edge-ssl
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-edge-ssl
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-reencrypt-ssl
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-reencrypt-ssl
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-demo-httpd
        ports:
        - containerPort: 443
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-passthrough-ssl
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-passthrough-ssl
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-demo-httpd
        ports:
        - containerPort: 443
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-waf
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-waf
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: f5-demo-app-route-edge-ssl-waf
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: f5-demo-app-route-edge-ssl-waf
    spec:
      containers:
      - name: f5-demo-app-route
        image: f5devcentral/f5-hello-world
        ports:
        - containerPort: 8080
          protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: svc1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: svc1
        image: f5devcentral/f5-demo-httpd
        ports:
        - containerPort: 443
          protocol: TCP   