apiVersion: cis.f5.com/v1
kind: IngressLink
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  host: '*.example.com'
  multiClusterServices:
  - clusterName: cluster1
    namespace: nginx-ingress
    service: nginx-ingress
  - clusterName: cluster2
    namespace: nginx-ingress
    service: nginx-ingress
  policyName: cr-policy1
  tls:
    clientSSLParams:
      renegotiationEnabled: false
    serverSSLParams:
      renegotiationEnabled: false  
    clientSSLs:
    - wc-example-secret
    reference: secret
    serverSSLs:
    - wc-example-secret
  virtualServerAddress: 10.8.3.11