apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bigip-ctlr-configmap-role
  namespace: kube-system
rules:
  - apiGroups: [ "", "extensions" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bigip-ctlr-configmap-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bigip-ctlr-configmap-role
subjects:
  - kind: ServiceAccount
    name: bigip-ctlr
    namespace: kube-system